name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ci-bot
          
          if [ -d "just-juggle-arc-bridge" ]; then
            echo "Directory just-juggle-arc-bridge exists."
          else
            git clone git@github.com:rudgalvis/just-juggle-arc-bridge.git
          fi
                  
          cd just-juggle-arc-bridge
                  
          git pull
          
          dst="./../file-server/distribution"
          
          # Create the destination directory if it doesn't exist
          mkdir -p "$dst"
          
          cp -Rf ./distribution/* "$dst"
